name: test
on:
    pull_request: ~
    push:
        branches:
            - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
    test:
        runs-on: ubuntu-latest
        name: test (${{ matrix.name }})
        strategy:
            matrix:
                include:
                    - name: php-8.2
                      php-version: '8.2'
                      install-args: ''
                      composer-cache-suffix: default
                    - name: php-8.3
                      php-version: '8.3'
                      install-args: ''
                      composer-cache-suffix: default
                    - name: php-8.4
                      php-version: '8.4'
                      install-args: ''
                      composer-cache-suffix: default
                    - name: php-8.5
                      php-version: '8.5'
                      install-args: ''
                      composer-cache-suffix: default
                    - name: php-8.5-prefer-lowest
                      php-version: '8.5'
                      install-args: '--prefer-lowest'
                      composer-cache-suffix: prefer-lowest
            fail-fast: false
        steps:
            - name: checkout
              uses: actions/checkout@v6

            - name: php
              uses: shivammathur/setup-php@2.37.1
              with:
                  php-version: ${{ matrix.php-version }}
                  ini-values: zend.assertions=1

            - name: composer-cache-dir
              id: composercache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: composer-cache
              uses: actions/cache@v5.0.5
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: composer-${{ hashFiles('**/composer.json') }}-${{ matrix.composer-cache-suffix }}
                  restore-keys: |
                      composer-${{ hashFiles('**/composer.json') }}-${{ matrix.composer-cache-suffix }}
                      composer-${{ hashFiles('**/composer.json') }}-
                      composer-

            - name: composer
              run: |
                  composer update ${{ matrix.install-args }} --no-interaction --no-progress --prefer-dist

            - name: phpunit
              run: |
                  vendor/bin/simple-phpunit --no-coverage

    static-analysis:
        runs-on: ubuntu-latest
        name: static-analysis
        steps:
            - name: checkout
              uses: actions/checkout@v6

            - name: php
              uses: shivammathur/setup-php@2.37.1
              with:
                  php-version: '8.5'
                  ini-values: zend.assertions=1

            - name: composer-cache-dir
              id: composercache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: composer-cache
              uses: actions/cache@v5.0.5
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: |
                      composer-${{ hashFiles('**/composer.json') }}
                      composer-

            - name: composer
              run: |
                  composer update --no-interaction --no-progress --prefer-dist

            - name: phpstan-cache
              uses: actions/cache@v5.0.5
              with:
                  key: phpstan-${{ github.ref }}-${{ github.sha }}
                  path: .phpstan-cache
                  restore-keys: |
                      phpstan-${{ github.ref }}-
                      phpstan-

            - name: phpstan
              run: |
                  mkdir -p .phpstan-cache
                  vendor/bin/phpstan analyse --no-progress --no-interaction --memory-limit=1G
